# **GPA Change Prediction**

outlook

In [64]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import category_encoders as ce
import scipy.stats as stats

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, learning_curve, cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

import preprocessing as pr

print("Importations Successful.")

Importations Successful.

In [54]:
# versions of the used third-party packages
from sklearn import __version__ as sklearn_version
from numpy import __version__ as np_version
from pandas import __version__ as pd_version
from seaborn import __version__ as sns_version
from matplotlib import __version__ as plt_version

print(f"Scikit-learn's Version: {sklearn_version}")
print(f"NumPy's Version: {np_version}")
print(f"Pandas's Version: {pd_version}")
print(f"Seaborn's Version: {sns_version}")
print(f"Matploblib's Version: {plt_version}")

Scikit-learn's Version: 1.9.0
NumPy's Version: 2.4.2
Pandas's Version: 3.0.0
Seaborn's Version: 0.13.2
Matploblib's Version: 3.10.8

In [55]:
sns.set_theme(
    context="notebook",
    style="whitegrid",
    font_scale=1.1
)

# Introduction:

We did a regression project to identify the GPA difference of each student using features in the dataset. Now in this project we have a plan to make that regression project to a classification project and instead of predicting the exact GPA difference we want to predict the GPA difference between these categories: ["low", "medium", "high"]

We hope to get great results using less features and the primary goal of this project is that we want to exercise a classification project.

- **Regression Problem Path:** core_ml/regression/impact_of_ai_on_students

# Problem Definition:

predict that based-on the data features what would be the student's GPA difference.

In [56]:
df = pd.read_csv("../data/ai_student_impact_dataset (1).csv")
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [57]:
# fixing datatypes for categorical variables
df['Major_Category'] = df['Major_Category'].str.lower().astype("category")
df['Year_of_Study'] = df['Year_of_Study'].str.lower().astype("category")
df['Primary_Use_Case'] = df['Primary_Use_Case'].str.lower().astype("category")
df['Prompt_Engineering_Skill'] = df['Prompt_Engineering_Skill'].str.lower().astype("category")
df['Institutional_Policy'] = df['Institutional_Policy'].str.lower().astype("category")
df['Burnout_Risk_Level'] = df['Burnout_Risk_Level'].str.lower().astype("category")

In [58]:
df['GPA_Difference'] = abs(df['Post_Semester_GPA'] - df['Pre_Semester_GPA'])
df['GPA_Difference'] = pd.cut(
    df['GPA_Difference'],
    bins=[-0.01, 0.3, 0.6, np.inf],
    labels=["low", "medium", "high"]
)

df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level,GPA_Difference
0,100001,humanities,senior,2.418,23.31,copywriting/drafting,beginner,1,True,8.13,5,allowed_with_citation,6,2.393,86.44,high,low
1,100002,medical,junior,3.821,1.12,ideation,advanced,5,False,16.65,3,allowed_with_citation,9,3.696,69.39,low,low
2,100003,business,freshman,3.398,21.26,summarizing_reading,beginner,2,False,10.35,5,strict_ban,9,3.499,73.93,medium,low
3,100004,business,senior,3.789,1.82,copywriting/drafting,intermediate,4,False,15.23,2,allowed_with_citation,2,4.000,63.58,medium,low
4,100005,stem,sophomore,3.635,9.29,debugging/troubleshooting,advanced,4,False,12.55,4,allowed_with_citation,4,3.798,100.00,medium,low

In [59]:
pr.category_percentage(df['GPA_Difference'])

  GPA_Difference  percent
0            low  % 69.71
1         medium  % 28.49
2           high   % 1.80

we have a task of imbalaced classification.

In [60]:
# encoding
df['Paid_Subscription'] = df['Paid_Subscription'].astype("category").cat.codes
df['GPA_Difference'] = df['GPA_Difference'].cat.codes
feature_names = [feature for feature in df.columns if feature not in ["Student_ID", "GPA_Difference"]]

X = df[feature_names]
y = df['GPA_Difference']

# encoding
oh_encoding_cols = ["Major_Category", "Primary_Use_Case", "Institutional_Policy"]
ordinal_cols = ["Year_of_Study", "Prompt_Engineering_Skill", "Burnout_Risk_Level"]
mapping = [
    {
        "col": "Year_of_Study",
        "mapping": {
            "freshman": 0,
            "sophomore": 1,
            "junior": 2,
            "senior": 3,
            "graduate": 4
		}
	},
    {
        "col": "Prompt_Engineering_Skill",
        "mapping":{
            "beginner": 0,
            "intermediate": 1,
            "advanced": 2
		}
	},
    {
        "col": "Burnout_Risk_Level",
        "mapping": {
            "low": 0,
            "medium": 1,
            "high": 2
		}
	}
]

encoder = Pipeline(
    steps=[
        ("one_hot", ce.OneHotEncoder(cols=oh_encoding_cols, use_cat_names=True)),
        ("ordinal_1", ce.OrdinalEncoder(mapping=mapping, cols=ordinal_cols))
	]
)
features_encoded = pd.DataFrame(
    data=encoder.fit_transform(X),
    columns=encoder.get_feature_names_out()
)

# droping the non-informative column in the one-hot encoded features (one is non-informative in each)
non_informative_features = ["Major_Category_arts", "Primary_Use_Case_direct_answer_generation", "Institutional_Policy_actively_encouraged"]
informative_features = [feature for feature in features_encoded.columns if feature not in non_informative_features]
features_encoded = features_encoded[informative_features]

features_encoded

,Major_Category_humanities,Major_Category_medical,Major_Category_business,Major_Category_stem,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case_copywriting/drafting,Primary_Use_Case_ideation,Primary_Use_Case_summarizing_reading,...,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy_allowed_with_citation,Institutional_Policy_strict_ban,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,1,0,0,0,3,2.418,23.31,1,0,0,...,1,1,8.13,5,1,0,6,2.393,86.44,2
1,0,1,0,0,2,3.821,1.12,0,1,0,...,5,0,16.65,3,1,0,9,3.696,69.39,0
2,0,0,1,0,0,3.398,21.26,0,0,1,...,2,0,10.35,5,0,1,9,3.499,73.93,1
3,0,0,1,0,3,3.789,1.82,1,0,0,...,4,0,15.23,2,1,0,2,4.000,63.58,1
4,0,0,0,1,1,3.635,9.29,0,0,0,...,4,0,12.55,4,1,0,4,3.798,100.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0,0,1,0,3,2.899,12.16,1,0,0,...,2,0,13.36,2,1,0,2,3.584,66.16,2
49996,0,0,0,1,3,2.870,2.51,1,0,0,...,1,0,4.67,3,0,0,3,3.096,81.62,1
49997,0,0,1,0,3,3.177,15.87,0,0,1,...,5,1,3.92,4,1,0,5,3.605,97.21,2
49998,0,0,1,0,2,3.398,19.91,0,0,0,...,5,0,7.10,5,1,0,3,3.527,84.12,1
49999,0,0,0,0,1,3.242,3.30,1,0,0,...,1,0,3.93,2,1,0,6,3.261,76.16,0

In [61]:
X = features_encoded.to_numpy()
y = df['GPA_Difference'].to_numpy()

# train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42 # to make it reproducable
)

# scaling features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [62]:
# model training
logreg = LogisticRegression(random_state=42)
logreg.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)